title: Tajemství K-popu a proč se stává čím dál tím víc populárním
baseURL: https://reverent-einstein-1993a0.netlify.com/
languageCode: cs-cz
publishDir: public
googleAnalytics: "UA-1399334873-1"

menu:
  main:
    - name: Domovská stránka
      url: /
      weight: 10
    - name: Archív
      identifier: post
      url: /post/
      weight: 20

params:
  description: Stránka zabývající se popularizací K-popu ve světě.
  authors: Kamila Vejmelková a Hana Jakubčíková

